// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKazxp7QxIWG6uha2aTjBy2GyhiDkrhNA',
    appId: '1:499892163089:web:95c930a529ea63e53157b0',
    messagingSenderId: '499892163089',
    projectId: 'mymovieapp-44545',
    authDomain: 'mymovieapp-44545.firebaseapp.com',
    storageBucket: 'mymovieapp-44545.appspot.com',
    measurementId: 'G-SGT96MSZBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkcTh6ZULqb9jrfiwuHB92RUO8qycnmTg',
    appId: '1:499892163089:android:79e0695bce15434e3157b0',
    messagingSenderId: '499892163089',
    projectId: 'mymovieapp-44545',
    storageBucket: 'mymovieapp-44545.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxtP1xvkv1N2rNm4oMcec9Fc2nfxA9Aww',
    appId: '1:499892163089:ios:7df4894d6d025bb53157b0',
    messagingSenderId: '499892163089',
    projectId: 'mymovieapp-44545',
    storageBucket: 'mymovieapp-44545.appspot.com',
    iosBundleId: 'com.example.movieApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxtP1xvkv1N2rNm4oMcec9Fc2nfxA9Aww',
    appId: '1:499892163089:ios:c6beaf5f68eb50073157b0',
    messagingSenderId: '499892163089',
    projectId: 'mymovieapp-44545',
    storageBucket: 'mymovieapp-44545.appspot.com',
    iosBundleId: 'com.example.movieApps.RunnerTests',
  );
}
